#!/bin/bash
# Bash script to update all of my virtual machines

BIN="~/bin/update_vm"

VMS="leap15_1 leap15_2 sle15sp1 sle15sp2"

echo "Updating the following virtual machines: "
for vm in $VMS; do echo " * $vm"; done
echo "* tumbleweed"       # separate because needs zypper dup instead of up

echo "Hit return to continue"
read

for vm in $VMS; do
	$BIN "$vm" "zypper ref && zypper patch -y"
done

# Tumbleweed needs zypper dup
$BIN "tumbleweed" "zypper ref && zypper dup -y"
